name: Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Generate and Deploy Documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate TypeDoc documentation
      run: |
        npm run docs:generate
        mkdir -p docs-output
        cp -r docs/* docs-output/
    
    - name: Create docs index
      run: |
        mkdir -p docs-final
        cp -r docs-output/* docs-final/
        
        # Create a landing page for the docs
        cat > docs-final/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Dachshund.dev Documentation</title>
            <style>
                body {
                    font-family: system-ui, sans-serif;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 40px 20px;
                    line-height: 1.6;
                }
                .logo {
                    text-align: center;
                    margin-bottom: 40px;
                }
                .links {
                    display: grid;
                    gap: 20px;
                    margin-top: 40px;
                }
                .link-card {
                    border: 1px solid #ddd;
                    border-radius: 8px;
                    padding: 20px;
                    text-decoration: none;
                    color: inherit;
                    transition: box-shadow 0.2s;
                }
                .link-card:hover {
                    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
                }
            </style>
        </head>
        <body>
            <div class="logo">
                <h1>🐕 Dachshund.dev</h1>
                <p>Lightning-fast search powered by AI</p>
            </div>
            
            <div class="links">
                <a href="./modules.html" class="link-card">
                    <h3>API Documentation</h3>
                    <p>Complete TypeScript API documentation generated with TypeDoc</p>
                </a>
                
                <a href="https://github.com/djensenius/search-frontend" class="link-card">
                    <h3>Source Code</h3>
                    <p>View the complete source code on GitHub</p>
                </a>
            </div>
        </body>
        </html>
        EOF
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs-final
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
